@startuml

actor A as "advisor"

rectangle Database

rectangle System {
usecase UC1 as "get sorted cities in district"
usecase UC2 as "print populations"

A - UC1
UC1 - Database
UC1 ..> UC2 : include
}

@enduml