@startuml

actor A as "marketer"

rectangle Database

rectangle System {
usecase UC3 as "present interface"
usecase UC1 as "get data"
usecase UC2 as "provide data background"

A - UC3
UC1 - Database
UC1 ..> UC2 : include
UC3 - UC1
}

@enduml